### PR TITLE
Declarative approach in demo and other changes

### PR DESCRIPTION
**Pull request by kcmr**
- Document lang is set using HTML lang attribute.
- Added unresolved attribute to body to make an opacity transition.
- Lang label selector is associated with its control.
- Improved lang selector styles.
- Component styles for demo purposes have been moved to demo-styles. Also some properties that require the use of the theme-base or specific CSS custom properties have been removed.
- Added dom-bind template to demo to use a declarative approach instead of the previous imperative way of setting properties.
- Cells demo image minified and moved to demo folder.
- Demo image is included as component light DOM.
- `project` demo property has been replaced by `heading` property. A `title` property is avoided because is a native HTML attribute.
- Tested property updated in tests. In my opinion, this test should not be included in the generator.
- Added .editorconfig with the values expected by linters.
- Table alignment in docs changed to left for better readability.
- cells-demo-mobile is optional.
- theme-base devDependency is not included if the user choose to not use a theme.

Sorry, not squashed.

### CODE REVIEW

**Comment by froucher** [comment]
@kcmr, thanks for the updates! it have many significant changes!
- @iliasmorenoalui, @jdzrtz, @sbonacho 
  So, we are going to check the pull-request, and then, we are going to update cells-cli with those changes.

Thx.

**Comment by iliasmorenoalui** [comment]
@carolirod and @oscarmarina are checking this PR

**Comment by carolirod** [comment]
@kcmr thanks for the proposals, changes have been reviewed (and will be applied directly to master) and some will be included in the next version of the generator-cells.

**Comment by carolirod** [comment]
@kcmr thanks for the proposals, changes have been reviewed already and some will be applied directly to master as well as included in the next version of the generator-cells.

**Pull request closed without merging**
